spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.type: trace

jwt:
  key: ${JWT_KEY}
  access-token-expiration-minutes: ${JWT_ACCESS_EXPIRATION_MIN}
  refresh-token-expiration-minutes: ${JWT_REFRESH_EXPIRATION_MIN}